name: CI
on:
  - push
  - pull_request
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install poetry
        uses: snok/install-poetry@v1

      - name: Install just
        uses: taiki-e/install-action@just

      - name: Install the dependencies
        run: just dev

      - name: Run tests
        run: just test
