name: CI
on: [push]
jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: taiki-e/install-action@just
      - run: just dev
      - run: just test
